import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import ScalarFormatter


"""
Code to read the datafile.
Generated by Microsoft 365 Copilot, checked by David D. Dai.
"""
# Initialize an empty list to store the counts
counts = []

# Read the file content
with open('uranium.txt', 'r') as file:
    lines = file.readlines()

# Flag to indicate if we are in the data section
data_section = False

# Iterate over each line in the file
for line in lines:
    # Check if we have reached the data section
    if line.strip() == "0 2047":
        data_section = True
        continue
    
    # Check if we have reached the end of the data section
    if line.strip() == "$ROI:":
        break
    
    # If we are in the data section, process the line
    if data_section:
        # Split the line into individual counts and add them to the list
        counts.extend(map(int, line.split()))

# Convert the list to a NumPy array
counts = np.array(counts)


"""
Plotting code.
Cosmetics generated by Microsoft 365 Copilot.
"""

# I am keeping all 2048 bins to show the sharp spikes.
# This detail is lost by plotting with combined bins.
# Plotting code with requested modifications
plt.bar(np.arange(len(counts)), counts, width=1,
        label=f"Ortec EASY-MCA-2k, Collection Time: $110$ x $10^3s$")
plt.title('X-Ray Spectrum of Fiestaware Dinner Platter')
plt.xlabel('Bin Number')
plt.ylabel('Counts')

# Format the y-axis in scientific notation and use a logarithmic scale
plt.yscale('log')
plt.gca().yaxis.set_major_formatter(ScalarFormatter(useMathText=True))
plt.ticklabel_format(axis='y', style='scientific', scilimits=(0,0))
plt.legend()
plt.savefig("fiestaware_x-ray spectrum_021025.jpeg", dpi=200, bbox_inches="tight")
plt.show()